/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIOS;

import CLASES.Categoria;
import CLASES.Conexion;
import CLASES.Placeholders;
import CLASES.Prenda;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 21Ernesto00
 */
public class FormPrendas extends javax.swing.JFrame {
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("IMAGENES/tienda.png"));
        return retValue;
    }
    public String [] opciones = {"Salir","Cancelar"};
    FormBuscar buscar=new FormBuscar(this, true);
    public static Categoria categoria =new Categoria();
    private Prenda prenda =new Prenda();
    public boolean control;
    public boolean valor=true;
    private Conexion conexion = new Conexion();
//    public int xx;
//    public int yy;
    private int liNombre=20;
    private int liModelo=15;
    private int liTalla=3;
    private int liStock=11;
    
    public void mostrarDatos(String busqueda){
        ArrayList<Prenda> listaPrenda = new ArrayList<>();
        listaPrenda=conexion.mostrarPrenda(busqueda);
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("ID PRENDA");
        tabla.addColumn("NOMBRE");
        tabla.addColumn("MODELO");
        tabla.addColumn("TALLA");
        tabla.addColumn("PRECIO");
        tabla.addColumn("STOCK");
        tabla.addColumn("ID CATEGORÍA");
        tabla.setRowCount(listaPrenda.size());
        for(int regActual=0; regActual<listaPrenda.size();regActual=regActual+1){
            tabla.setValueAt(listaPrenda.get(regActual).getIdPrendas(), regActual, 0);
            tabla.setValueAt(listaPrenda.get(regActual).getNombre(), regActual, 1);
            tabla.setValueAt(listaPrenda.get(regActual).getModelo(), regActual, 2);
            tabla.setValueAt(listaPrenda.get(regActual).getTalla(), regActual, 3);
            tabla.setValueAt(listaPrenda.get(regActual).getPrecio(), regActual, 4);
            tabla.setValueAt(listaPrenda.get(regActual).getStock(), regActual, 5);
            tabla.setValueAt(listaPrenda.get(regActual).getFk_idCategoria(), regActual, 6);
        }
        tablaPrenda.setModel(tabla);        
    }
    
    public void limpiarTexto(){
        ctIdPrenda.setText("");
        ctNombrePrenda.setText("");
        ctModeloPrenda.setText("");
        ctTallaPrenda.setText("");
        ctPrecioPrenda.setText("");
        ctStockPrenda.setText("");

        ctIdCategoria.setText("");
        ctNombreCategoria.setText("");
        ctDescripcionCategoria.setText("");
    }
    /**
     * Creates new form FormPrendas
     */
    public FormPrendas() {
        initComponents();
        this.setTitle("BOUTIQUE-PRENDA");
        mostrarDatos("");
        setLocationRelativeTo(null);
        this.setResizable(false);
        setDefaultCloseOperation(0);
        
        Placeholders placeholders1 = new Placeholders("Ej. 001", ctIdPrenda);
        Placeholders placeholders2 = new Placeholders("Ej. Vestido", ctNombrePrenda);
        Placeholders placeholders3 = new Placeholders("Ej. Corte Imperio", ctModeloPrenda);
        Placeholders placeholders4 = new Placeholders("Ej. XS", ctTallaPrenda);
        Placeholders placeholders5 = new Placeholders("Ej. $45.60", ctPrecioPrenda);
        Placeholders placeholders6 = new Placeholders("Ej. (18)", ctStockPrenda);
        
        Placeholders placeholders7 = new Placeholders("Ej. 001", ctIdCategoria);
        Placeholders placeholders8 = new Placeholders("Ej. Bebés", ctNombreCategoria);
        Placeholders placeholders9 = new Placeholders("Ej. (0-24 meses)", ctDescripcionCategoria);
        Placeholders placeholders10 = new Placeholders("Ej. Bebés", ctBuscarPrenda);
//        this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ctIdPrenda = new javax.swing.JTextField();
        ctNombrePrenda = new javax.swing.JTextField();
        ctModeloPrenda = new javax.swing.JTextField();
        ctTallaPrenda = new javax.swing.JTextField();
        ctPrecioPrenda = new javax.swing.JTextField();
        ctStockPrenda = new javax.swing.JTextField();
        lblHeader = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ctIdCategoria = new javax.swing.JTextField();
        ctNombreCategoria = new javax.swing.JTextField();
        ctDescripcionCategoria = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPrenda = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        ctBuscarPrenda = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Prenda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/identificación.png"))); // NOI18N
        jLabel2.setText("ID PRENDAS:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/nombre.png"))); // NOI18N
        jLabel3.setText("NOMBRE:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/modelo.png"))); // NOI18N
        jLabel4.setText("MODELO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/talla.png"))); // NOI18N
        jLabel5.setText("TALLA:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/precio.png"))); // NOI18N
        jLabel6.setText("PRECIO:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/stock.png"))); // NOI18N
        jLabel7.setText("STOCK:");

        ctIdPrenda.setEditable(false);
        ctIdPrenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctIdPrenda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctIdPrenda.setEnabled(false);

        ctNombrePrenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctNombrePrenda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctNombrePrenda.setEnabled(false);
        ctNombrePrenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctNombrePrendaKeyTyped(evt);
            }
        });

        ctModeloPrenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctModeloPrenda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctModeloPrenda.setEnabled(false);
        ctModeloPrenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctModeloPrendaKeyTyped(evt);
            }
        });

        ctTallaPrenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctTallaPrenda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctTallaPrenda.setEnabled(false);
        ctTallaPrenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctTallaPrendaKeyTyped(evt);
            }
        });

        ctPrecioPrenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctPrecioPrenda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctPrecioPrenda.setEnabled(false);
        ctPrecioPrenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctPrecioPrendaKeyTyped(evt);
            }
        });

        ctStockPrenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctStockPrenda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctStockPrenda.setEnabled(false);
        ctStockPrenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctStockPrendaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ctIdPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 202, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ctStockPrenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctPrecioPrenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctTallaPrenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctModeloPrenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctNombrePrenda))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ctIdPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ctNombrePrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ctModeloPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ctTallaPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ctPrecioPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ctStockPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblHeader.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/prendas.png"))); // NOI18N
        lblHeader.setText("Prendas");
        lblHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblHeaderMouseDragged(evt);
            }
        });
        lblHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHeaderMousePressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Categoría", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/identificación.png"))); // NOI18N
        jLabel8.setText("ID CATEGORÍA:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/nombre.png"))); // NOI18N
        jLabel9.setText("NOMBRE:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/descripcion.png"))); // NOI18N
        jLabel10.setText("DESCRIPCIÓN:");

        ctIdCategoria.setEditable(false);
        ctIdCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctIdCategoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctIdCategoria.setEnabled(false);

        ctNombreCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctNombreCategoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctNombreCategoria.setEnabled(false);

        ctDescripcionCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctDescripcionCategoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctDescripcionCategoria.setEnabled(false);

        btnBuscar.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctNombreCategoria)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ctIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(ctDescripcionCategoria, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ctIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ctNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ctDescripcionCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnNuevo.setBackground(new java.awt.Color(255, 102, 51));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 0, 204));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 153, 51));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Modificar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(153, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(153, 0, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tablaPrenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaPrenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPrendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPrenda);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/busqueda.png"))); // NOI18N
        jLabel11.setText("BUSCAR:");

        ctBuscarPrenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctBuscarPrenda.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ctBuscarPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctBuscarPrendaActionPerformed(evt);
            }
        });
        ctBuscarPrenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ctBuscarPrendaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ctBuscarPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ctBuscarPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVolver.setBackground(new java.awt.Color(102, 0, 102));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/volver.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        btnNuevo.setEnabled(!valor);
        btnGuardar.setEnabled(valor);
        btnCancelar.setEnabled(valor);
        btnEditar.setEnabled(!valor);
        btnEliminar.setEnabled(!valor);
        
        limpiarTexto();
        
        ctNombrePrenda.setEnabled(valor);
        ctModeloPrenda.setEnabled(valor);
        ctTallaPrenda.setEnabled(valor);
        ctPrecioPrenda.setEnabled(valor);
        ctStockPrenda.setEnabled(valor);
        
        control=true;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            // TODO add your handling code here:
        prenda.setNombre(ctNombrePrenda.getText());
        prenda.setModelo(ctModeloPrenda.getText());
        prenda.setTalla(ctTallaPrenda.getText());
        prenda.setPrecio(Double.parseDouble(ctPrecioPrenda.getText()));
        prenda.setStock(Integer.parseInt(ctStockPrenda.getText()));
        prenda.setFk_idCategoria(Integer.parseInt(ctIdCategoria.getText()));
             
        if(ctNombrePrenda.getText().equals("")==true || ctModeloPrenda.getText().equals("")==true || ctTallaPrenda.getText().equals("")==true || ctPrecioPrenda.getText().equals("")==true || ctStockPrenda.getText().equals("")==true){
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }else{        
            if(control==true){
               //NUEVO
               conexion.guardarPrenda(prenda);
            }else{
               //MODIFICAR
               prenda.setIdPrendas(Integer.parseInt(ctIdPrenda.getText()));
               conexion.actualizarPrenda(prenda);

            }
        }
        
        btnNuevo.setEnabled(valor);
        btnGuardar.setEnabled(!valor);
        btnCancelar.setEnabled(!valor);
        btnEditar.setEnabled(valor);
        btnEliminar.setEnabled(valor);
        btnSalir.setEnabled(valor);
        
        limpiarTexto();
        
        ctNombrePrenda.setEnabled(!valor);
        ctModeloPrenda.setEnabled(!valor);
        ctTallaPrenda.setEnabled(!valor);
        ctPrecioPrenda.setEnabled(!valor);
        ctStockPrenda.setEnabled(!valor);
        
        mostrarDatos("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        btnNuevo.setEnabled(valor);
        btnGuardar.setEnabled(!valor);
        btnCancelar.setEnabled(!valor);
        btnEditar.setEnabled(valor);
        btnEliminar.setEnabled(valor);
        btnSalir.setEnabled(valor);

        ctNombrePrenda.setEnabled(!valor);
        ctModeloPrenda.setEnabled(!valor);
        ctTallaPrenda.setEnabled(!valor);
        ctPrecioPrenda.setEnabled(!valor);
        ctStockPrenda.setEnabled(!valor);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if(ctIdPrenda.getText().equals("")==true){
            JOptionPane.showMessageDialog(null,"Seleccione una prenda de la tabla para editar");
        }else{
            
            ctNombrePrenda.setEnabled(valor);
            ctModeloPrenda.setEnabled(valor);
            ctTallaPrenda.setEnabled(valor);
            ctPrecioPrenda.setEnabled(valor);
            ctStockPrenda.setEnabled(valor);

            btnNuevo.setEnabled(!valor);
            btnGuardar.setEnabled(valor);
            btnCancelar.setEnabled(valor);
            btnEditar.setEnabled(!valor);
            btnEliminar.setEnabled(!valor);
            btnSalir.setEnabled(!valor);
            control=false;
            
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        boolean resultado;
        if(ctIdPrenda.getText().equals("")==true){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una prenda de la tabla para eliminar");
        }else{
            
            resultado = conexion.eliminarPrenda(Integer.parseInt(ctIdPrenda.getText()));
            
            if(resultado==true){
                JOptionPane.showMessageDialog(null, "Prenda borrada correctamente");
                mostrarDatos("");
            }else
            {
                JOptionPane.showMessageDialog(null, "No se pudo borrar la prenda");
            }
            
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        new FormBuscar(this, true).setVisible(true);
        ctIdCategoria.setText(String.valueOf(categoria.getIdcategoria()));
        ctNombreCategoria.setText(categoria.getNombre());
        ctDescripcionCategoria.setText(categoria.getDescripcion());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showOptionDialog(null, "¿Salir de la aplicación?", "Pregunta",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
        if(i==0){
            this.dispose();   
        }else{}
    }//GEN-LAST:event_btnSalirActionPerformed

    private void ctBuscarPrendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctBuscarPrendaKeyReleased
        // TODO add your handling code here:
        mostrarDatos(ctBuscarPrenda.getText());
        
        if(ctBuscarPrenda.getText().equals("")==true){
            limpiarTexto();          
        }else{
            if(tablaPrenda.getRowCount()>0){  //Si la cantidad de filas de la tabla es mayor a cero.
                ctIdPrenda.setText(tablaPrenda.getValueAt(0, 0).toString());
                ctNombrePrenda.setText(tablaPrenda.getValueAt(0, 1).toString());
                ctModeloPrenda.setText(tablaPrenda.getValueAt(0, 2).toString());
                ctTallaPrenda.setText(tablaPrenda.getValueAt(0, 3).toString());
                ctPrecioPrenda.setText(tablaPrenda.getValueAt(0, 4).toString());
                ctStockPrenda.setText(tablaPrenda.getValueAt(0, 5).toString());
            }           
        }  
        
        
    }//GEN-LAST:event_ctBuscarPrendaKeyReleased

    private void tablaPrendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPrendaMouseClicked
        // TODO add your handling code here:
        int fila;
        fila=tablaPrenda.rowAtPoint(evt.getPoint());
        ctIdPrenda.setText(tablaPrenda.getValueAt(fila, 0).toString()   );
        ctNombrePrenda.setText(tablaPrenda.getValueAt(fila, 1).toString());
        ctModeloPrenda.setText(tablaPrenda.getValueAt(fila, 2).toString());
        ctTallaPrenda.setText(tablaPrenda.getValueAt(fila, 3).toString());
        ctPrecioPrenda.setText(tablaPrenda.getValueAt(fila, 4).toString());
        ctStockPrenda.setText(tablaPrenda.getValueAt(fila, 5).toString());
        ctIdCategoria.setText(tablaPrenda.getValueAt(fila, 6).toString());
    }//GEN-LAST:event_tablaPrendaMouseClicked

    private void lblHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHeaderMousePressed
        // TODO add your handling code here:
//        xx = evt.getX();
//	yy = evt.getY();
    }//GEN-LAST:event_lblHeaderMousePressed

    private void lblHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHeaderMouseDragged
        // TODO add your handling code here:
//        Point point = MouseInfo.getPointerInfo().getLocation();
//	setLocation(point.x-xx, point.y-yy);
    }//GEN-LAST:event_lblHeaderMouseDragged

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FormCategoria().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void ctPrecioPrendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctPrecioPrendaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();            
            evt.consume();
        }
    }//GEN-LAST:event_ctPrecioPrendaKeyTyped

    private void ctStockPrendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctStockPrendaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();            
            evt.consume();
        }
        if(ctStockPrenda.getText().length()==liStock){
            evt.consume();
        }
    }//GEN-LAST:event_ctStockPrendaKeyTyped

    private void ctNombrePrendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctNombrePrendaKeyTyped
        // TODO add your handling code here:
        if(ctNombrePrenda.getText().length()==liNombre){
            evt.consume();
        }
    }//GEN-LAST:event_ctNombrePrendaKeyTyped

    private void ctModeloPrendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctModeloPrendaKeyTyped
        // TODO add your handling code here:
        if(ctModeloPrenda.getText().length()==liModelo){
            evt.consume();
        }
    }//GEN-LAST:event_ctModeloPrendaKeyTyped

    private void ctTallaPrendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctTallaPrendaKeyTyped
        // TODO add your handling code here:
        if(ctTallaPrenda.getText().length()==liTalla){
            evt.consume();
        }
    }//GEN-LAST:event_ctTallaPrendaKeyTyped

    private void ctBuscarPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctBuscarPrendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctBuscarPrendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField ctBuscarPrenda;
    private javax.swing.JTextField ctDescripcionCategoria;
    private javax.swing.JTextField ctIdCategoria;
    private javax.swing.JTextField ctIdPrenda;
    private javax.swing.JTextField ctModeloPrenda;
    private javax.swing.JTextField ctNombreCategoria;
    private javax.swing.JTextField ctNombrePrenda;
    private javax.swing.JTextField ctPrecioPrenda;
    private javax.swing.JTextField ctStockPrenda;
    private javax.swing.JTextField ctTallaPrenda;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTable tablaPrenda;
    // End of variables declaration//GEN-END:variables
}
